name: Build Tests and Deploy app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore ./TechChallenge01.sln
        
      - name: Build
        run: dotnet build ./TechChallenge01.sln --configuration Release --no-restore
        
      - name: Test
        run: dotnet test ./TechChallenge01.sln --configuration Release --no-restore --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
        
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'coverage/*/coverage.cobertura.xml'
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY        

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: 'ciroa'
          password: ${{ secrets.SECRET_DOCKERHUB }}
      
      - name: Build and Push Docker Images for Each Service
        env:
          DOCKER_REPO: 'ciroa/tech-challenge-group43'
        run: |
          declare -a services=("TechChallenge01.Api" "TechChallenge01.ApiMessaging" "TechChallenge01.TokenApi" "TechChallenge01.WebStatus" "TechChallenge01.ApiGateway" "TechChallenge01.Infra.Consumer")

          for service in "${services[@]}"; do
            IMAGE_NAME=$(echo "$service" | tr '[:upper:]' '[:lower:]')
            docker build -t $DOCKER_REPO:$IMAGE_NAME-latest -f ./src/$service/Dockerfile .
            docker push $DOCKER_REPO:$IMAGE_NAME-latest
          done
